// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB88N-Z5EEuq7qzxjtYsaf74RMtR7HRYIQ',
    appId: '1:988356977057:web:824c964516222d896e6be0',
    messagingSenderId: '988356977057',
    projectId: 'deeplink-test-ac269',
    authDomain: 'deeplink-test-ac269.firebaseapp.com',
    databaseURL: 'https://deeplink-test-ac269.firebaseio.com',
    storageBucket: 'deeplink-test-ac269.appspot.com',
    measurementId: 'G-FNCD4DLNL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs8gAXczoAgaWpeFpXYO_IKQcLLy97Nyo',
    appId: '1:988356977057:android:a7c210f0a7a120096e6be0',
    messagingSenderId: '988356977057',
    projectId: 'deeplink-test-ac269',
    databaseURL: 'https://deeplink-test-ac269.firebaseio.com',
    storageBucket: 'deeplink-test-ac269.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ApkMfC3RkWVqfGxHQkdsoOnGDi0xnk0',
    appId: '1:988356977057:ios:9a3544ef2b87289d6e6be0',
    messagingSenderId: '988356977057',
    projectId: 'deeplink-test-ac269',
    databaseURL: 'https://deeplink-test-ac269.firebaseio.com',
    storageBucket: 'deeplink-test-ac269.appspot.com',
    iosClientId: '988356977057-nfrsr7i48j0lk276gve2a9psqom48lgn.apps.googleusercontent.com',
    iosBundleId: 'io.verloop.verloopFlutterSdkExample',
  );
}
